# Site settings
title: A Simple Blog :)
email: fairzy@qq.com
description: This is A Simple Blog :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fairzy.github.io" # the base hostname & protocol for your site
github_username:  fairzy

# Build settings
markdown: kramdown
