# Site settings
title: A simple blog
description: "A minimal blog template, build with Jekyll."
url: "http://fairzy.github.io"
author:
  name: "fairzy"
  email: "fairzy@qq.com"
  url: "http://www.weibo.com/doumering"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
